version: '3.8'

services:
  mongodb:
    # container_name: mongodb
    image: 'mongo'
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongo.env
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: max
    #   MONGO_INITDB_ROOT_PASSWORD: secret
    # networks:
    #   - networkName

  backend:
    # container_name: backend
    build: ./backend
    # build:
    #   context: ./backend
    #   dockerfile: dockerfile-dev
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app # 바인드 마운트
      - /app/node_modules # 익명 볼륨
    env_file:
      - ./env/backend.env
    depends_on: # 의존성 명시
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src # 바인드 마운트
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs:
